### ISSUE TITLE
Видео вставки и "открыть видео в отдельном окне"

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#1]
![image](https://user-images.githubusercontent.com/3256443/123747330-76e2ef80-d8bb-11eb-88ab-b823e2911938.png)

Надо отключить эту фичу, мешает.

По моему это делается добавления атрибута pip="false" к тегу video.

**Comment by aperekrestov** [comment]
Ты прав, фича мешает отключил. Спасибо за подсказку (pip="false")
