### ISSUE TITLE
http://perekrestov.ru/csoft/contacts.html

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#11]
Карта не сразу грузится.
Может туда картинку статическую поместить, повер которой будет карта грузиться.

**Comment by Segr** [comment]
Группа пишется с большой

**Comment by aperekrestov** [comment]
@Segr хорошая идея, добавил картинку и обновил **Г**руппу 
![Снимок экрана 2021-09-07 в 15 40 39](https://user-images.githubusercontent.com/16046152/132346146-cbde2bef-07cb-4cc9-9ac0-45913e88555d.png)
