### ISSUE TITLE
http://perekrestov.ru/csoft/search.html

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#12]
На сайте то искать практически нечего, страниц 10 не больше.

А вообще использовать лучше поиск от яндекс.

Пробовал хоть раз его стилизовать?

я пару раз пытался - https://try.mscad.ru/info/search.html

**Comment by aperekrestov** [comment]
Не пользовался, у него похоже функционал такой что поиск от яндекса будет искать информацию только на заранее заданных сайтах, а не во всем интернете

**Comment by Segr** [comment]
Так не надо во всем интернете.
При создании поиска указываешь где искать и он делает у тебя на сайте выдачу только для этого сайта.

**Comment by aperekrestov** [comment]
@Segr о чем и речь, во всем интернете искать - терять клиента. Я не сталкивался с таким поиском

**Comment by Segr** [comment]
так я же ссылку дал, посмотри как работает.

**Comment by aperekrestov** [comment]
Не делал ничего похожего, не могу обещать результат

**Comment by Segr** [comment]
тогда оставь, будем уже на сайте думать как и что реализовать
