### ISSUE TITLE
4 ссылки под формой

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#13]
![image](https://user-images.githubusercontent.com/3256443/132243618-9a065a5f-ff30-4c54-900b-f5b970eed39f.png)

должны быть кликабельны
 У ютуба другой значёк =)
 
 рекомендую использовать для иконок https://fontawesome.com/

**Comment by aperekrestov** [comment]
@Segr согласен в обоих случаях, я когда делал иконку сначала и отобразил ютюбовский значок, но он как-то встал не очень, сейчас попробую его опять добавить. Но похоже тут не совсем корректно что-то другое использовать кроме оригинального значка

**Comment by Segr** [comment]
попробуй все таки FA использовать

**Comment by aperekrestov** [comment]
@Segr все поправил, обновил
