### ISSUE TITLE
http://perekrestov.ru/csoft/error.html

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#14]
Повтори патерн который ты использовал на других страницах

Слева текстовка, справа цифровая инфа

![image](https://user-images.githubusercontent.com/3256443/132244097-2618e3da-5a23-46e1-902b-3ea8c96c6e89.png)

**Comment by aperekrestov** [comment]
@Segr давай так, наверное так будет правильней. Обновил
