### ISSUE TITLE
Формы

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#3]
На примере первой попавшейся

![image](https://user-images.githubusercontent.com/3256443/123787178-2bdcd280-d8e3-11eb-9cf8-eb4deaf148e5.png)

1. Ваше, Ваш, Ваше - лишние слова.

2. Ты используешь плейсхолдеры, как лейблы. в результате нарушается функция элемента.
Плейсхолдер должен подсказывать и расшифровывать более точно что надо вводить в поле.
А у тебя при попытке ввода любого символа плейсхолдер исчезает и человек уже не знает что надо вводить.
есть интересные решения, когда очень не хочется использовать лейблы, но они как бы есть: https://xhtml.ru/2021/html/how-to-create-fancy-jumping-text-input-labels/

3. капча - такие капчи уже давно обходятся на 100% автоматически, используй гугловскую reCaptcha. вот так она примерно выглядит https://usota.ru/wp-content/uploads/DfAvq9iX0AEtgFQ.jpg

4. Отправить сообщение должна выглядеть как кнопка, а у тебя она выглядит как ссылка - а это не тот  интерфейсный элемент который будут искать глазами.

5. поле сообщения, должно быть много строчным. textarea, сейчас вообще невозможно написать многострочный текст.

6. у любой формы с отправкой персональных данных должна быть галочка с чекбоксом, примерно такая
![image](https://user-images.githubusercontent.com/3256443/123788517-c853a480-d8e4-11eb-9b10-39435f79f4a1.png)

**Comment by aperekrestov** [comment]
Привет, Сергей. 

1. Согласен, слишком много повторений. На мой взгляд лишним не будет хотя бы один раз персонализировать форму, указав Ваше имя, например, но убрать местоимение в остальных полях.

2. Это вообще очень классный пример, спасибо за ссылку, переписал формы полностью

3. Не смог корректно установить. Мучился-пытался, но я не умею писать back-end от слова совсем =( Но все прошло не бессмысленно. Сейчас самая мощная капча - это reCAPTCA V3, которая освобождает пользователя от необходимости кликать на блок "я не робот" и собирать светофоры, витрины или лодки. А уровень защиты от бота регулируется в личном кабинете администратора и указывается от 0 до 1, со средним значением настоящего пользователя 0.5, все что ниже этого значения является подозрительным и блокируется. Да и капча привязывается к домену на котором будет опубликован сайт. Короче, к своему тестовому домену я не смог привязать корректно данную фичу. Но выглядит она классно поскольку приклеивается в правом нижнем углу сайта и не висит в самой форме. Скрин прикреплю.

4. Как говориться это не баг, а фича. Но спорить не буду, поскольку во "всплывающих" формах визуально использую кнопки

5. В поле сообщение можно писать много строк, также его можно растягивать за уголок в правом нижнем углу. Но раз тебе показалось что это поле ущемлено в своих правах, я внес коррективы =) 

6. Добавил, буду знать 

![Снимок экрана 2021-07-01 в 13 10 17](https://user-images.githubusercontent.com/16046152/124464617-14975c80-dd9d-11eb-9c05-a4c75b9c755f.png)

**Comment by Segr** [comment]
"Не смог корректно установить."
поставь просто картинку,

**Comment by aperekrestov** [comment]
Если использовать самую свежую капчу, там и картинка не нужна в самой форме, это же классный прогрессивный UX

**Comment by Segr** [comment]
"Как говориться это не баг, а фича. Но спорить не буду, поскольку во "всплывающих" формах визуально использую кнопки"
в модальных формах там вообще другие кнопки

я в дизайне у тебя увидел два типа кнопок
- button-style-1 - кнопка котоаря выглядит как ссылка
- button-style-2 - кнопка которая выглядит как кнопка
- button-style-3 - кнопка для форм, вот мне кажется она по стилю - лишняя

**Comment by Segr** [comment]
"Добавил, буду знать"
куда добавил? Не вижу на сайте

**Comment by aperekrestov** [comment]
> "Добавил, буду знать"
> куда добавил? Не вижу на сайте

http://test.perekrestov.ru
