### ISSUE TITLE
Формы - label

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#4]
![image](https://user-images.githubusercontent.com/3256443/132241263-9dabe810-0d2f-46b4-8f16-d760a34ceb35.png)

**Comment by aperekrestov** [comment]
@Segr Привет. Спасибо за комментарии. С отступами ты прав, так будет лучше. Цвет указан правильный. 
![Снимок экрана 2021-09-07 в 11 55 40](https://user-images.githubusercontent.com/16046152/132316069-6cc908c6-c5c3-43c5-a4c9-47fded5d791f.png)

**Comment by Segr** [comment]
цвет возможно указан и правильный, но вот на практике там красный и он не читается

**Comment by aperekrestov** [comment]
@Segr красным выделяем текст в нужный момент, он нормально справляется со своей задачей
![Снимок экрана 2021-09-07 в 15 43 09](https://user-images.githubusercontent.com/16046152/132346941-025ce6da-706a-4adb-a7fd-43c6684cd9b3.png)

**Comment by Segr** [comment]
Красный на черном - не читается.

**Comment by perchick** [comment]
![Uploading Снимок экрана 2021-09-07 в 15.47.59.png…]()

**Comment by aperekrestov** [comment]
В данном случае все корректно
![Снимок экрана 2021-09-07 в 15 50 46](https://user-images.githubusercontent.com/16046152/132347858-a85332e9-4e8c-4525-8e65-be4ce1204faa.png)

**Comment by aperekrestov** [comment]
![Снимок экрана 2021-09-07 в 15 47 59](https://user-images.githubusercontent.com/16046152/132347952-e3269f30-a641-4f74-99ee-5f42146538a0.png)

**Comment by Segr** [comment]
Значит меня относим в группу с нарушением восприятия.
с одного расстояния слово "сообщение" я читаю, а "email" не могу прочитать, только догадываюсь
