### ISSUE TITLE
подвал

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#6]
![image](https://user-images.githubusercontent.com/3256443/132241766-bdda7aec-10e5-434a-87fe-4e5393c5dad1.png)

**Comment by aperekrestov** [comment]
@Segr флаг показывает что проект российский, когда переведем на польский, английский и тд, флаг будет выполнять функцию смены языка контента. 
Иконка справа будет отображать политику конфиденциальности, и добавим вторую иконку для пользовательского соглашения.

**Comment by Segr** [comment]
тогда может тултипы сделать, либо стандартные через title, либо чем-то боле е мощным.

не забывай у картинок прописывать alt, со смысловым наполнением.
