### ISSUE TITLE
Меню

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#8]
Если активна страница услуги, то она должна быть выделена.

раз на сайте нет хлебных крошек, должно быть визуально выделено где мы находимся.

**Comment by aperekrestov** [comment]
@Segr да так действительно будет лучше, обновил
![Снимок экрана 2021-09-07 в 15 13 37](https://user-images.githubusercontent.com/16046152/132342582-30382525-bb84-4ebe-b8ec-9fb92d9af185.png)
