### ISSUE TITLE
http://perekrestov.ru/csoft/products.html

### ISSUE THREAD

**Issue by Segr** [perchick/csoft-digitalization-website-1.0.0#9]
![image](https://user-images.githubusercontent.com/3256443/132242181-74feb16a-9b76-4067-920a-515d83e191fd.png)
мне кажется, что более важным является название, а не действие
поэтому нарядом со стрелками надо название ПО

**Comment by Segr** [comment]
У цифровизации же больше чем 2 продукта, давай реальными данными наполнять.
https://csoft-digital.ru/soft.html

**Comment by aperekrestov** [comment]
@Segr эти элементы должны в первую очередь отвечать за навигацию. В идеале в кнопку НАЗАД динамически подгружать предыдущую страницу на которой был юзер (главная, контакты, како-то продукт и тд), да и на более мелких экранах эти блоки не поместятся физически с длинным названием если рядом со стрелкой писать что-то длиннее, чем есть сейчас

**Comment by Segr** [comment]
Элементы навигации рази навигации - мне не нравится.
